name: ripenv

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version:
          - '0.15.0'
          - '0.15.1'
          - '0.15.2'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Zig ${{ matrix.zig-version }}
        run: |
          ZIG_VERSION=${{ matrix.zig-version }}
          ZIG_URL="https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz"
          mkdir -p zig-linux-${ZIG_VERSION}
          curl -s -L "${ZIG_URL}" | tar -xJ --strip-components=1 -C zig-linux-${ZIG_VERSION}
          echo "$(pwd)/zig-linux-${ZIG_VERSION}" >> ${GITHUB_PATH}

      - name: Check Zig version
        run: zig version

      - name: Build
        run: zig build --release -Dci=true

      - name: env vars
        run: env

      - name: Check help
        run: ./zig-out/bin/ripenv --help

      - name: Test
        run: ./zig-out/bin/ripenv < tests/test1.txt

      - name: Test Prefix
        run: ./zig-out/bin/ripenv -c % < tests/test2.txt

      - name: Test Buffer Size
        run: ./zig-out/bin/ripenv -b 4096 < tests/test1.txt
